// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	filewalker "github.com/c-toast/directory-walker/filewalker"
	mock "github.com/stretchr/testify/mock"
)

// TestFilesProvider is an autogenerated mock type for the filesProvider type
type TestFilesProvider struct {
	mock.Mock
}

// Init provides a mock function with given fields: dirPath, dirReaderImpl
func (_m *TestFilesProvider) Init(dirPath string, dirReaderImpl ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, dirPath)
	_ca = append(_ca, dirReaderImpl...)
	ret := _m.Called(_ca...)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, ...interface{}) error); ok {
		r0 = rf(dirPath, dirReaderImpl...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Next provides a mock function with given fields:
func (_m *TestFilesProvider) Next() (*filewalker.FileInfoWrapper, error) {
	ret := _m.Called()

	var r0 *filewalker.FileInfoWrapper
	if rf, ok := ret.Get(0).(func() *filewalker.FileInfoWrapper); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*filewalker.FileInfoWrapper)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
