// Code generated by mockery v2.5.1. DO NOT EDIT.

package mocks

import (
	filewalker "github.com/c-toast/directory-walker/filewalker"
	mock "github.com/stretchr/testify/mock"
)

// TestFileHandler is an autogenerated mock type for the fileHandler type
type TestFileHandler struct {
	mock.Mock
}

// CanHandle provides a mock function with given fields: info
func (_m *TestFileHandler) CanHandle(info *filewalker.FileInfoWrapper) bool {
	ret := _m.Called(info)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*filewalker.FileInfoWrapper) bool); ok {
		r0 = rf(info)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Handle provides a mock function with given fields: info
func (_m *TestFileHandler) Handle(info *filewalker.FileInfoWrapper) error {
	ret := _m.Called(info)

	var r0 error
	if rf, ok := ret.Get(0).(func(*filewalker.FileInfoWrapper) error); ok {
		r0 = rf(info)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
